[package]
name = "rucat_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rucat_common = {path = "../rucat_common"}
tonic = "0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }