apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: state-monitor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: state-monitor-role
subjects:
- kind: ServiceAccount
  name: rucat-state-monitor
  namespace: default