apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: state-monitor-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets", "namespaces"]
  verbs: ["get", "watch", "list", "create", "delete"]