apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "check_interval_secs": 5,
      "database": {
        "credentials": {
          "username": "admin",
          "password": "admin"
        },
        "uri": "rucat-surrealdb:8000"
      }
    }