apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "check_interval_millis": 1000,
      "database": {
        "credentials": {
          "username": "admin",
          "password": "admin"
        },
        "variant": {
          "type": "Local",
          "uri": "rucat-surrealdb:8000"
        }
      }
    }