[package]
name = "rucat_cluster_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rucat_cluster" = {path = "../rucat_cluster"}
