[package]
name = "rucat_state_monitor"
version = "0.2.0"
edition = "2021"

[dependencies]
rucat_common = {path = "../rucat_common"}
kube = "0.98.0"
k8s-openapi = { version = "0.24.0", features = ["latest"] }

[dev-dependencies]
mockall = "0.13.1"