[package]
name = "rucat_state_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
rucat_common = {path = "../rucat_common"}
kube = "0.97.0"
k8s-openapi = { version = "0.23.0", features = ["latest"] }