[package]
name = "rucat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rucat_common = {path = "../rucat_common"}
axum = {"version" = "0.7.5", features = ["macros"]}
axum-extra = {"version" = "0.9.3", features = ["typed-header"]}
bytes = {"version" = "1.6.0"}
http = {"version" = "1.1.0"}
http-body = {"version" = "1.0.0"}
serde = {"version" = "1.0.201", features = ["derive"]}
surrealdb = {"version" = "1.4.2", features = ["kv-mem"]}
tower-http = { "version" = "0.5.0", features = ["trace"] }
tracing = {"version" = "0.1.40"}
tracing-subscriber = {"version" = "0.3.18"}
tokio = {"version" = "1.36.0", features = ["full"]}

# test dependencies

[dev-dependencies]
axum-test = {"version" = "14.9.1"}
headers = {"version" = "0.4.0"}
serde_json = {"version" = "1.0.117"}
