[package]
name = "rucat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rucat_common = {path = "../rucat_common"}
axum = {"version" = "0.7.5", features = ["macros"]}
axum-extra = {"version" = "0.9.3", features = ["typed-header"]}
bytes = {"version" = "1.7.1"}
http = {"version" = "1.1.0"}
http-body = {"version" = "1.0.1"}
serde = {"version" = "1.0.209", features = ["derive"]}
serde_json = "1.0.127"
tower-http = { "version" = "0.5.2", features = ["trace"] }
tracing = {"version" = "0.1.40"}
tracing-subscriber = {"version" = "0.3.18"}
tokio = {"version" = "1.39.3", features = ["full"]}
tonic = "0.12.2"

# test dependencies

[dev-dependencies]
axum-test = {"version" = "15.6.0"}
headers = {"version" = "0.4.0"}
