[package]
name = "rucat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rucat_common = {path = "../rucat_common"}
axum = {"version" = "0", features = ["macros"]}
axum-extra = {"version" = "0", features = ["typed-header"]}
bytes = {"version" = "1"}
http = {"version" = "1"}
http-body = {"version" = "1"}
serde = {"version" = "1", features = ["derive"]}
serde_json = {"version" = "1"}
surrealdb = {"version" = "1", features = ["kv-mem"]}
tower-http = { "version" = "0", features = ["trace"] }
tracing = {"version" = "0"}
tracing-subscriber = {"version" = "0"}
tokio = {"version" = "1", features = ["full"]}
tonic = "0"
clap = { version = "4", features = ["derive"] }
clap_derive = "4"

# test dependencies

[dev-dependencies]
axum-test = {"version" = "14"}
headers = {"version" = "0"}
serde_json = {"version" = "1"}
