[package]
name = "rucat_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surrealdb = {"version" = "1.4.2"}
axum = {"version" = "0.7.5"}
anyhow = {"version" = "1.0.83"}
tonic = "0.11.0"
prost = "0.12.6"

[build-dependencies]
tonic-build = "0.11.0"