[package]
name = "rucat_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {"version" = "0.7.9"}
anyhow = {"version" = "1.0.93"}
clap = { version = "4.5.21", features = ["derive"] }
clap_derive = "4.5.18"
kube = "0.97.0"
k8s-openapi = { version = "0.23.0", features = ["latest"] }
prost = "0.13.3"
rand = "0.8.5"
serde = {"version" = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"
surrealdb = {"version" = "2.1.0", features = ["kv-mem", "native-tls"]}
tokio = {"version" = "1.41.1", features = ["full"]}
tonic = "0.12.3"
time = {version = "0.3.36", features = ["serde-well-known", "parsing", "macros"]}
tracing = {"version" = "0.1.40"}
tracing-subscriber = {"version" = "0.3.18"}

[build-dependencies]
tonic-build = "0.12.3"