name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Install Surrealdb
      run: |
        curl -ssf https://install.surrealdb.com | sh
        PATH=${_loc}:\$PATH
    - name: Switch to nightly rust toolchain
      run: rustup default nightly
    - name: Build
      run: cargo build
    - name: Refactor
      run: cargo clippy -- -D clippy::all
    - name: Format
      run: cargo fmt --check
    - name: Run tests
      run: bash test.sh
